CREATE TABLE SP_USER (  id INT NOT NULL ,  username VARCHAR(45) NOT NULL,  password VARCHAR(100) NOT NULL,  algorithm VARCHAR(45) NOT NULL,  PRIMARY KEY (id));

CREATE TABLE SP_AUTHORITY (  id INT NOT NULL AUTO_INCREMENT,  name VARCHAR(45) NOT NULL,  user_id INT NOT NULL,  PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES SP_USER(id));

CREATE TABLE SP_PRODUCT (
  id INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  price VARCHAR(45) NOT NULL,
  currency VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));